# --- SMIX(lambda) specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 8

buffer_size: 1500

# update the target network every {} episodes
target_update_interval: 200

# use the S_Learner to train
agent_output_type: "q"
learner: "s_learner"
mixing_embed_dim: 32

name: "smix"
mixer: "qmix"
save_model: True

# agent type
agent: rnn
rnn_hidden_dim: 64

td_lambda: 0.8
